name: NPM Publish

on:
  release:
    types: [published]
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  publish-tag:
    if: github.event_name == 'release'
    uses: ./.github/workflows/publish-tag.yml

  publish-main:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/publish-main.yml
    