name: Build and Publish Latest

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  npm-publish-latest:
    if: github.event.pull_request.merged == true
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/npm-publish.yml
    with:
      type: latest
