name: Build and Publish Tag

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  npm-publish-tag:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/npm-publish.yml
    with:
      type: tag
